#!/bin/env bash

# Set the name of the private key
PRIVATE_KEY_NAME="school"

# Set the number of bits for the key
KEY_BITS=4096

# Set the passphrase for the key
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b ${KEY_BITS} -f "${PRIVATE_KEY_NAME}" -N "${PASSPHRASE}"

echo "RSA key pair created successfully!"
